# Lo spazio metrico $\mathbf{R}^N$

Sia $N \in \mathbf{N}$, vogliamo definire un vettore $\underline{x} \in \mathbf{R}^N$ usando `numpy`

In [1]:
import numpy as np

In [2]:
N = 10

zero = np.zeros(N)
one = np.ones(N)


In [3]:
print(zero)
print(one)

print(zero.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [4]:
x = np.array([2.0, 5, 1, 0, 7, 2, 3, 47, 3, 0])
y = np.array([3, 42, 12, 2, 5, 0, -2, -23, 0, 1])

print(x.shape)
print(y.shape)

(10,)
(10,)


In [5]:
z = np.arange(N)

print(z)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(x.dtype)
print(y.dtype)

float64
int32


In [7]:
s = np.linspace(0, 100, num=N)

print(s)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [8]:
print(s.shape)
print(s.dtype)

(10,)
float64


### Somma tra vettori:

In [11]:
z = x + y
print(z)

print(z.dtype)

[ 5. 47. 13.  2. 12.  2.  1. 24.  3.  1.]
float64


### Prodotto per scalari:

In [12]:
print(3 * x + 2 * y)

[12. 99. 27.  4. 31.  6.  5. 95.  9.  2.]


### Prodotto scalare:

In [ ]:
print(x * y)
print( np.sum(x * y) )
print( np.dot(x, y) )

# fare il conto: ... for XXX
# calcolare i tempi di esecuzione di ciascun metodo

[    6.   210.    12.     0.    35.     0.    -6. -1081.     0.     0.]
-824.0
-824.0


### Norma di un vettore:

In [15]:
print( np.linalg.norm(x) )

print( np.sqrt( np.dot(x, x) ) )

48.062459362791664
48.062459362791664


In [16]:
print( np.dot([1, 0, 0], [0, 1, 1]) )

0
